spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    connect-timeout: 1800000
    jedis:
      pool:
        max-active: 200
        max-wait: 100000
        max-idle: 32
        min-idle: 0